package com.wujie.greendaogen;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BACKUP".
 */
@Entity
public class Backup {

    @Id
    private Long id;

    @NotNull
    private String filename;

    @NotNull
    private String d_src;

    @NotNull
    private String src;
    private double size;
    private java.util.Date date;
    private Integer progress;
    private Boolean up_status;

    @Generated
    public Backup() {
    }

    public Backup(Long id) {
        this.id = id;
    }

    @Generated
    public Backup(Long id, String filename, String d_src, String src, double size, java.util.Date date, Integer progress, Boolean up_status) {
        this.id = id;
        this.filename = filename;
        this.d_src = d_src;
        this.src = src;
        this.size = size;
        this.date = date;
        this.progress = progress;
        this.up_status = up_status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getFilename() {
        return filename;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFilename(@NotNull String filename) {
        this.filename = filename;
    }

    @NotNull
    public String getD_src() {
        return d_src;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setD_src(@NotNull String d_src) {
        this.d_src = d_src;
    }

    @NotNull
    public String getSrc() {
        return src;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSrc(@NotNull String src) {
        this.src = src;
    }

    public double getSize() {
        return size;
    }

    public void setSize(double size) {
        this.size = size;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    public Boolean getUp_status() {
        return up_status;
    }

    public void setUp_status(Boolean up_status) {
        this.up_status = up_status;
    }

}
