package com.wujie.greendaogen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wujie.greendaogen.Person;
import com.wujie.greendaogen.Backup;

import com.wujie.greendaogen.PersonDao;
import com.wujie.greendaogen.BackupDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig backupDaoConfig;

    private final PersonDao personDao;
    private final BackupDao backupDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        backupDaoConfig = daoConfigMap.get(BackupDao.class).clone();
        backupDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        backupDao = new BackupDao(backupDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(Backup.class, backupDao);
    }
    
    public void clear() {
        personDaoConfig.clearIdentityScope();
        backupDaoConfig.clearIdentityScope();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public BackupDao getBackupDao() {
        return backupDao;
    }

}
