package com.wujie.greendaogen;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PERSON".
 */
@Entity
public class Person {

    @Id
    private Long id;

    @NotNull
    private String name;

    @Property(nameInDb = "_sex")
    private String sex;
    private String height;

    @Generated
    public Person() {
    }

    public Person(Long id) {
        this.id = id;
    }

    @Generated
    public Person(Long id, String name, String sex, String height) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.height = height;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getHeight() {
        return height;
    }

    public void setHeight(String height) {
        this.height = height;
    }

}
